using System.Diagnostics;
using System.Net.Http;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Threading;
namespace MyCustomLauncher;

public partial class MainWindow : Window {
    private readonly LauncherConfig config; private readonly ApiClient api; private string? sessionToken; private string? username; private readonly string gameDir; private readonly DispatcherTimer healthTimer=new(){Interval=TimeSpan.FromSeconds(30)}; private CancellationTokenSource? launchCancellation; private Process? gameProcess; private readonly LauncherPreferences preferences;
    public MainWindow() {
        InitializeComponent();
        preferences=LauncherPreferences.Load();UsernameBox.Text=preferences.Username;SelectRam(preferences.RamGb);
        try { config=LauncherConfig.Load(); api=new ApiClient(config.ApiBaseUrl); gameDir=Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),".mycustomclient"); Loaded+=RestoreSessionAsync; healthTimer.Tick+=async(_,_)=>await UpdateServerStatusAsync(); healthTimer.Start(); AppLog.Info("Launcher started"); }
        catch(Exception ex){MessageBox.Show(ex.Message,"Ошибка конфигурации",MessageBoxButton.OK,MessageBoxImage.Error);Close();config=null!;api=null!;gameDir="";}
    }
    private async void RestoreSessionAsync(object sender,RoutedEventArgs e){await UpdateServerStatusAsync();string? saved=SecureTokenStore.Load();if(saved is null)return;LoginStatus.Text="Проверка сохранённой сессии…";if(await api.ValidateAsync(saved)){sessionToken=saved;username=ReadJwtUsername(saved)??"Игрок";ShowLauncher();}else{SecureTokenStore.Clear();LoginStatus.Text="Сохранённая сессия истекла. Войдите снова.";}}
    private async void Login_Click(object sender,RoutedEventArgs e){if(string.IsNullOrWhiteSpace(UsernameBox.Text)||string.IsNullOrEmpty(PasswordBox.Password)){LoginStatus.Text="Введите логин и пароль";return;}SetLoginBusy(true);try{string hwid=HwidService.GetHwid(config.HwidApplicationSalt);var result=await api.LoginAsync(UsernameBox.Text.Trim(),PasswordBox.Password,hwid);sessionToken=result.SessionToken;username=result.Username;preferences.Username=result.Username;preferences.Save();if(RememberBox.IsChecked==true)SecureTokenStore.Save(sessionToken);else SecureTokenStore.Clear();PasswordBox.Clear();ShowLauncher();}catch(Exception ex)when(ex is LauncherApiException or InvalidOperationException){LoginStatus.Text=ex.Message;}finally{SetLoginBusy(false);}}
    private async void Play_Click(object sender,RoutedEventArgs e){if(sessionToken is null||username is null||gameProcess is {HasExited:false})return;PlayButton.IsEnabled=false;CancelButton.Visibility=Visibility.Visible;launchCancellation=new CancellationTokenSource();try{LaunchStatus.Text="Проверка сессии…";if(!await api.ValidateAsync(sessionToken,launchCancellation.Token)){SecureTokenStore.Clear();throw new LauncherApiException("Сессия истекла. Выполните вход повторно.");}var service=new ContentService(config.ContentBaseUrl,gameDir);var progress=new Progress<ContentProgress>(value=>{Progress.Value=value.Percent;LaunchStatus.Text=value.TotalFiles==0?value.Message:$"{value.Message}  •  {value.CompletedFiles}/{value.TotalFiles}  •  {FormatBytes(value.CompletedBytes)}/{FormatBytes(value.TotalBytes)}";});ContentManifest manifest=await service.SynchronizeAsync(config.ManifestPath,progress,launchCancellation.Token);LaunchStatus.Text="Поиск Java…";string javaPath=JavaResolver.Resolve(config.JavaPath);int ram=int.Parse(((ComboBoxItem)RamBox.SelectedItem).Tag.ToString()!);preferences.RamGb=ram;preferences.Save();LaunchStatus.Text="Запуск Java…";gameProcess=GameLauncher.Start(javaPath,gameDir,manifest,username,sessionToken,ram);gameProcess.EnableRaisingEvents=true;gameProcess.Exited+=(_,_)=>Dispatcher.Invoke(()=>{LaunchStatus.Text="Игра завершена";PlayButton.IsEnabled=true;gameProcess.Dispose();gameProcess=null;});AppLog.Info($"Game started, PID {gameProcess.Id}, RAM {ram} GB");LaunchStatus.Text=$"Игра запущена (PID {gameProcess.Id})";}catch(OperationCanceledException){LaunchStatus.Text="Обновление отменено";PlayButton.IsEnabled=true;}catch(Exception ex)when(ex is LauncherApiException or HttpRequestException or IOException or InvalidDataException or InvalidOperationException){AppLog.Error("Game launch failed",ex);LaunchStatus.Text=ex.Message;PlayButton.IsEnabled=true;}finally{CancelButton.Visibility=Visibility.Collapsed;launchCancellation.Dispose();launchCancellation=null;}}
    private void Cancel_Click(object sender,RoutedEventArgs e)=>launchCancellation?.Cancel();
    private void Logout_Click(object sender,RoutedEventArgs e){SecureTokenStore.Clear();sessionToken=null;username=null;LauncherPanel.Visibility=Visibility.Collapsed;LoginPanel.Visibility=Visibility.Visible;LogoutButton.Visibility=Visibility.Collapsed;LoginStatus.Text="";}
    private void ShowLauncher(){LoginPanel.Visibility=Visibility.Collapsed;LauncherPanel.Visibility=Visibility.Visible;LogoutButton.Visibility=Visibility.Visible;GreetingText.Text=$"Привет, {username}";}
    private void SetLoginBusy(bool value){LoginButton.IsEnabled=!value;LoginStatus.Text=value?"Авторизация…":"";}
    private async Task UpdateServerStatusAsync(){bool healthy=await api.IsHealthyAsync();ServerStatus.Text=healthy?"Сервер доступен":"Сервер недоступен";ServerDot.Fill=new SolidColorBrush((Color)ColorConverter.ConvertFromString(healthy?"#65D8C0":"#FF7186"));}
    private void SelectRam(int ramGb){foreach(ComboBoxItem item in RamBox.Items)if(item.Tag?.ToString()==ramGb.ToString()){RamBox.SelectedItem=item;break;}}
    private static string FormatBytes(long bytes){string[] units=["B","KB","MB","GB"];double value=bytes;int unit=0;while(value>=1024&&unit<units.Length-1){value/=1024;unit++;}return $"{value:0.#} {units[unit]}";}
    private static string? ReadJwtUsername(string token){try{string payload=token.Split('.')[1].Replace('-','+').Replace('_','/');payload=payload.PadRight(payload.Length+(4-payload.Length%4)%4,'=');using var document=System.Text.Json.JsonDocument.Parse(Convert.FromBase64String(payload));return document.RootElement.GetProperty("username").GetString();}catch{return null;}}
}
